baseURL = "https://staging.grass.osgeo.org/"
theme = "grass"


[params]

primaryColor = "#088B36"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#333333"
grassColor = "#088B36"
grassColorAlt= "#9ed29c"
grassColorLight= "#eff4e8"
grassColorDark= "#87a06a"
whiteColor = "#ffffff"
greyColor = "#6b6b6b"
greyColorLight = "#CCCCCC"
greyColorDark = "#A0A0A0"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  defaultMarkdownHandler = "blackfriday"
  
[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "GRASS GIS - Bringing advanced geospatial technologies to the world"
  dateFormat = "1 January 2019"
  logo = "GRASS GIS"
  copyright = "Copyright Â© 1998-2020, GRASS Development Team."
  license = "GNU GPL"

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 1
        name = "Download"
        url = "/download"
        
      [[Languages.en.menu.main]]
        weight = 2
        name = "Learn"
        url = "/learn"

          [[Languages.en.menu.main]]
          parent = "Learn"
          name = "General overview"
          URL = "/learn/overview"
          weight = 1

          [[Languages.en.menu.main]]
          parent = "Learn"
          name = "First time users"
          URL = "/learn/newcomers"
          weight = 2

          [[Languages.en.menu.main]]
          parent = "Learn"
          name = "Manuals"
          URL = "/learn/manuals"
          weight = 3 

          [[Languages.en.menu.main]]
          parent = "Learn"
          name = "Tutorials"
          URL = "/learn/tutorials"
          weight = 4 
 
          [[Languages.en.menu.main]]
          parent = "Learn"
          name = "Books"
          URL = "/learn/books"
          weight = 5

    
      [[Languages.en.menu.main]]
        weight = 3
        name = "Contribute"
        url = "/contribute"
        hasChildren = true

          [[Languages.en.menu.main]]
          parent = "Contribute"
          name = "Wiki"
          URL = "https://grasswiki.osgeo.org/wiki/GRASS-Wiki"
          weight = 1 

          [[Languages.en.menu.main]]
          parent = "Contribute"
          name = "Development"
          URL = "/contribute/development"
          weight = 2

          [[Languages.en.menu.main]]
          parent = "Contribute"
          name = "Donations"
          URL = "/contribute/donations"
          weight = 3

          [[Languages.en.menu.main]]
          parent = "Contribute"
          name = "Sponsors"
          URL = "https://grasswiki.osgeo.org/wiki/Sponsors"
          weight = 4


      [[Languages.en.menu.main]]
        weight = 4
        name = "About"
        url = "/about"
        hasChildren = true
	
          [[Languages.en.menu.main]]
          parent = "About"
          name = "News"
          URL = "/news"
          weight = 1

          [[Languages.en.menu.main]]
          parent = "About"
          name = "Community"
          URL = "/about/community"
          weight = 2

          [[Languages.en.menu.main]]
          parent = "About"
          name = "Brand"
          URL = "/about/brand"
          weight = 3

          [[Languages.en.menu.main]]
          parent = "About"
          name = "Credits"
          URL = "/about/credits"
          weight = 4

    # banner
    [Languages.en.params.banner]
      title = "GRASS GIS"
      description = "Bringing advanced geospatial technologies to the world"
      image = "/images/banner.jpg"

    # Topics
    [Languages.en.params.topics]
      title = "Geographic Resources Analysis Support System"


    # footer social icon
    [[Languages.en.socialIcon]]
      icon = " fa fa-github"
      URL = "https://github.com/OSGeo/grass"
      
    [[Languages.en.socialIcon]]
      icon = " fa fa-twitter"
      URL = "https://twitter.com/grassgis"    

    [[Languages.en.socialIcon]]
      icon = "fa fa-facebook"
      URL = "https://www.facebook.com/GRASSGISCommunity"

    [[Languages.en.socialIcon]]
      icon = "fa fa-youtube"
      URL = "https://www.youtube.com/results?search_query=grass+gis"   





 
