baseURL = "https://grass.osgeo.org/"
theme = "grass"
enableInlineShortcodes = true

[params]
description = "GRASS GIS is a free Geographic Information System (GIS) software used for geospatial data management and analysis, image processing, graphics/maps production, spatial modeling, and visualization."
keywords = "open source gps, GRASS, FOSS4G, open source gis, open source gis grass, open source web gis, open source gis software, free open source gis, gis, mapping, open source software, mapping software, cartography, gis data, geospatial, open source 3d, geographic information system, geographic information systems, gis software, mapping data, free software, raster, topology, vector, image processing, visualization, hydrology, archeology, archaeology, 3D GIS"
primaryColor = "#088B36"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#333333"
grassColor = "#088B36"
grassColorAlt= "#9ed29c"
grassColorLight= "#eff4e8"
grassColorDark= "#87a06a"
whiteColor = "#ffffff"
blackColor = "#000000"
greyColor = "#6b6b6b"
greyColorLight = "#CCCCCC"
greyColorDark = "#A0A0A0"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap_hugo.xml"
  priority = 0.5


[markup]
  defaultMarkdownHandler = "goldmark"
 
[markup.goldmark.renderer]
  unsafe = true


[outputFormats]
  [outputFormats.sitemap]
    baseName = "sitemap"
    isPlainText = false
    mediaType = "application/xml"
    protocol = "xml://"
    path = "/"

[outputs]
  home = ["HTML", "sitemap", "RSS"]


[Languages]

  # English Language
  [Languages.en.params]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "GRASS GIS - Bringing advanced geospatial technologies to the world"
  dateFormat = "1 January 2019"
  logo = "GRASS GIS"
  copyright = "1998-{year}, GRASS Development Team"
  license = "GNU GPL"

    # navigation
    [Languages.en.menu]

    [[Languages.en.menu.main]]
      weight = 1
      name = "About Us"
      url = "/about"
      hasChildren = true

      [[Languages.en.menu.main]]
        parent = "About Us"
        name = "Team"
        weight = 1
        URL = "/about/team"

      [[Languages.en.menu.main]]
        parent = "About Us"
        name = "Roadmap"
        weight = 2
        URL = "/about/roadmap"

      [[Languages.en.menu.main]]
        parent = "About Us"
        name = "Governance"
        weight = 3
        URL = "/about/governance"

      [[Languages.en.menu.main]]
        parent = "About Us"
        name = "License"
        URL = "/about/license"
        weight = 4

      [[Languages.en.menu.main]]
        parent = "About Us"
        name = "History"
        URL = "/about/history"
        weight = 5

      [[Languages.en.menu.main]]
        parent = "About Us"
        name = "Brand"
        URL = "/about/brand"
        weight = 6

      [[Languages.en.menu.main]]
        parent = "About Us"
        name = "Credits"
        URL = "/about/credits"
        weight = 7

      [[Languages.en.menu.main]]
        parent = "About Us"
        name = "Citation"
        URL = "/about/citation"
        weight = 8

    [[Languages.en.menu.main]]
      weight = 2
      name = "Download"
      url = "/download"

      [[Languages.en.menu.main]]
        parent = "Download"
        name = "GRASS GIS source code"
        URL = "https://github.com/OSGeo/grass/tags"
        weight = 1

	    [[Languages.en.menu.main]]
        parent = "Download"
        name = "GRASS GIS for Linux"
        URL = "/download/linux"
        weight = 2

 	    [[Languages.en.menu.main]]
        parent = "Download"
        name = "GRASS GIS for Windows"
        URL = "/download/windows"
        weight = 3

 	    [[Languages.en.menu.main]]
        parent = "Download"
        name = "GRASS GIS for Mac"
        URL = "/download/mac"
        weight = 4

 	    [[Languages.en.menu.main]]
        parent = "Download"
        name = "Docker images"
        URL = "/download/docker"
        weight = 5

      [[Languages.en.menu.main]]
        parent = "Download"
        name = "Addons"
        URL = "/download/addons"
        weight = 6

 	    [[Languages.en.menu.main]]
        parent = "Download"
        name = "Sample data"
        URL = "/download/data"
        weight = 7
        
    [[Languages.en.menu.main]]
      weight = 3
      name = "Learn"
      url = "/learn"

      [[Languages.en.menu.main]]
        parent = "Learn"
        name = "General overview"
        URL = "/learn/overview"
        weight = 1

      [[Languages.en.menu.main]]
        parent = "Learn"
        name = "First time users"
        URL = "/learn/newcomers"
        weight = 2

      [[Languages.en.menu.main]]
        parent = "Learn"
        name = "Manuals"
        URL = "/learn/manuals"
        weight = 3 

      [[Languages.en.menu.main]]
        parent = "Learn"
        name = "Tutorials"
        URL = "/learn/tutorials"
        weight = 4 

      [[Languages.en.menu.main]]
        parent = "Learn"
        name = "Gallery"
        URL = "/learn/gallery"
        weight = 5
	  
      [[Languages.en.menu.main]]
        parent = "Learn"
        name = "Books"
        URL = "/learn/books"
        weight = 6
 
      [[Languages.en.menu.main]]
        parent = "Learn"
        name = "Try online"
        URL = "/learn/tryonline"
        weight = 7

    [[Languages.en.menu.main]]
      weight = 4
      name = "Support"
      url = "/support"
      hasChildren = true

      [[Languages.en.menu.main]]
        parent = "Support"
        name = "Community"
        URL = "/support/community"
        weight = 1

      [[Languages.en.menu.main]]
        parent = "Support"
        name = "Commercial Support"
        URL = "/support/commercial"
        weight = 2    
      
    [[Languages.en.menu.main]]
      weight = 5
      name = "Contribute"
      url = "/contribute"
      hasChildren = true

      [[Languages.en.menu.main]]
        parent = "Contribute"
        name = "Development"
        URL = "/contribute/development"
        weight = 1

      [[Languages.en.menu.main]]
        parent = "Contribute"
        name = "Sponsoring"
        URL = "/contribute/sponsoring"
        weight = 2
	  
      [[Languages.en.menu.main]]
        parent = "Contribute"
        name = "Sponsors"
        URL = "https://grasswiki.osgeo.org/wiki/Sponsors"
        weight = 4

    # banner
    [Languages.en.params.banner]
      title = "GRASS GIS"
      description = "Bringing advanced geospatial technologies to the world"
      image = "/images/banner.jpg"

    # Topics
    [Languages.en.params.topics]
      title = "Geographic Resources Analysis Support System"

    # footer social icon
    [[Languages.en.params.socialIcon]]
      icon = " fab fa-github"
      link = "https://github.com/OSGeo/grass"

    [[Languages.en.params.socialIcon]]
          icon = " fa fa-comments"
          link = "https://gitter.im/grassgis/community"

    [[Languages.en.params.socialIcon]]
      icon = " fab fa-mastodon"
      link = "https://fosstodon.org/@grassgis"

    [[Languages.en.params.socialIcon]]
      icon = " fab fa-x-twitter"
      link = "https://twitter.com/grassgis"    

    [[Languages.en.params.socialIcon]]
      icon = "fab fa-facebook"
      link = "https://www.facebook.com/groups/GRASS"

    #[[Languages.en.params.socialIcon]]
    #  icon = "fab fa-youtube"
    #  link = "https://www.youtube.com/results?search_query=grass+gis"
      
    [[Languages.en.params.socialIcon]]
      icon = "fa fa-rss"
      link = "https://grass.osgeo.org/index.xml" 
